# Generated by Django 3.2.5 on 2021-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_auto_20210816_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('discount_price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
